### ISSUE TITLE
exits before finishing work

### ISSUE THREAD

**Issue by kmyounes** [sidahmed-malaoui/ip_hash_table#1]
En entrant une ligne vide (sans espace) en recherchant si une ip est blacklisté, le programme se termine.

**Comment by sidahmed-malaoui** [comment]
Thats the point. The program finishes when you enter an empty line.
So if you don't wanna search, you just enter an empty line. This is what you ment ??!!

**Comment by kmyounes** [comment]
if i hit a wrong double enter ? i'm nervous u know..

**Comment by sidahmed-malaoui** [comment]
hhhhhhhhhhhh, that's the program lol.

This program is a complexity exercice that was asked by my teacher, that's why I just created an implementation that works, without looking soo much on the easy of use of the program.

If I would improve this program for real use, I would add some options like adding the IPs from a file (that would be much simpler for the user).
